name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.12.0
              with:
                  assignees: gioxx
                  numOfAssignee: 1
                  allowSelfAssign: true

            - name: 'Comment on issue'
              uses: actions/github-script@v7.0.1
              with:
                  script: |
                      const issueNumber = context.issue.number;
                      const message = "🇮🇹 Grazie per aver aperto la segnalazione. Ti informo, però, che il progetto è in fase di chiusura. Vedi https://github.com/gioxx/MarvellousSuspender/discussions/196.\n\n" +
                                      "🇬🇧 Thank you for opening the issue. Please be advised, however, that the project will soon be closed due to Chrome V3 manifest and new policies. Please take a look here: https://github.com/gioxx/MarvellousSuspender/discussions/196.";
                      await github.rest.issues.createComment({
                          ...context.repo,
                          issue_number: issueNumber,
                          body: message
                      });
